### PR TITLE
Added Stack

### PR DESCRIPTION
**Pull request by blog-a1**

### CODE REVIEW

**Review by sugandha-kadp — COMMENTED** [review]
not related this one.

**Comment by blog-a1** [comment]
Can you tell me what kind of things should I contribute.

**Comment by sugandha-kadp** [comment]
This is design for Hacktoberfest. This code has some mistakes, you must correct that mistake. Then I can mention as You have been successfully accepted hacktoberfest 2021.

**Comment by blog-a1** [comment]
OK 👍

**Comment by sugandha-kadp** [comment]
:+1:

**Pull request closed without merging**
