### PR TITLE
Solved Discount Problem

### PR DESCRIPTION
**Pull request by satyam-mahajan**

### CODE REVIEW

**Comment by sugandha-kadp** [comment]
it has the same mistake also.

**Comment by satyam-mahajan** [comment]
ohk let me rectified it.

**Comment by satyam-mahajan** [comment]
its done mam ,if any conflicts let me know .

**Comment by sugandha-kadp** [comment]
not yet, please check the entire code.

**Comment by satyam-mahajan** [comment]
@Sugandha-kadp Mam , I create a new file DISCOUNT.cpp ,Its now correct .please check.

**Comment by sugandha-kadp** [comment]
all syntax mistakes are fixed, but it will print payment value no?

**Comment by satyam-mahajan** [comment]
once minute I can fix it.

**Comment by satyam-mahajan** [comment]
@Sugandha-kadp Mam I change payment no to discount ,please change .

**Comment by sugandha-kadp** [comment]
@satyam-mahajan  I think you have updated the wrong code, can you fix it with the correct syntax one quickly I can accept it now?

**Comment by satyam-mahajan** [comment]
@Sugandha-kadp Mam I change and update the code.I works fine on all the test cases.

**Review by sugandha-kadp — COMMENTED** [review]
Done

**Pull request closed without merging**
